swagger: "2.0"
info:
  version: "1.0.0"
  title: "My API"
host: "api.example.com"
basePath: "/v1"
schemes:
  - "https"
paths:
  /users:
    get:
      summary: "Retrieves a list of users"
      responses:
        200:
          description: "A list of users"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
    get:
      summary: "Creates a new user"
      parameters:
        - name: "user"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "The newly created user"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
